package Biblioteca;


/**
* Biblioteca/GestionBibliotecaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* domingo 30 de marzo de 2025 00H52' CET
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public interface GestionBibliotecaOperations 
{

  // Busca un libro por título y devuelve los detalles del libro
  Biblioteca.Libro buscarLibro (String titulo);

  // Presta un libro, cambiando su estado a no disponible
  boolean prestarLibro (String ISBN);

  // Devuelve un libro, cambiando su estado a disponible
  boolean devolverLibro (String ISBN);

  // Mostrar todos los libros
  Biblioteca.Libro[] mostrarLibros ();

  // Nuevas operaciones
  String obtenerAutor (String titulo);
  Biblioteca.Libro[] buscarPorAutor (String autor);
  Biblioteca.Libro[] obtenerLibrosNoDisponibles ();
  String verDetallesLibro (String ISBN);

  // Operaciones adicionales de gestión
  boolean anadirLibro (Biblioteca.Libro libro);
  boolean eliminarLibro (String ISBN);
  boolean actualizarLibro (Biblioteca.Libro libro);
} // interface GestionBibliotecaOperations
